config/routes.rb
AutismeApp::Application.routes.draw do
  resources :infopersos do
    resources :infos  
    resources :etats
  end

  get "users/new"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get "presentation/inscription"

  root 'presentation#home'

end

app/models/etat.rb
class Etat < ActiveRecord::Base
  belongs_to :infoperso
end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :infoperso
end

app/models/infoperso.rb
class Infoperso < ActiveRecord::Base
has_many :infos
has_many :etats
end

app/models/user.rb
class User < ActiveRecord::Base
  
  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :pseudo,  presence: true , length: { maximum: 50 }
  validates :email, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/etats_controller.rb
class EtatsController < ApplicationController
def create
    @infoperso = Infoperso.find(params[:infoperso_id])
    @etat = @infoperso.etats.create(params[:etat].permit(:humor,:event))
    redirect_to infoperso_path(@infoperso)
  end

  def destroy
		@infoperso = Infoperso.find(params[:infoperso_id])
		@etat = @infoperso.etats.find(params[:id])
		@etat.destroy
		redirect_to infoperso_path(@infoperso)
	end

end

app/controllers/infopersos_controller.rb
class InfopersosController < ApplicationController
  before_action :set_infoperso, only: [:show, :edit, :update, :destroy]

  # GET /infopersos
  # GET /infopersos.json
  def index
    @infopersos = Infoperso.all
  end

  # GET /infopersos/1
  # GET /infopersos/1.json
  def show
  end

  # GET /infopersos/new
  def new
    @infoperso = Infoperso.new
  end

  # GET /infopersos/1/edit
  def edit
  end

  # POST /infopersos
  # POST /infopersos.json
  def create
    @infoperso = Infoperso.new(infoperso_params)

    respond_to do |format|
      if @infoperso.save
        format.html { redirect_to @infoperso, notice: 'Infoperso was successfully created.' }
        format.json { render action: 'show', status: :created, location: @infoperso }
      else
        format.html { render action: 'new' }
        format.json { render json: @infoperso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infopersos/1
  # PATCH/PUT /infopersos/1.json
  def update
    respond_to do |format|
      if @infoperso.update(infoperso_params)
        format.html { redirect_to @infoperso, notice: 'Infoperso was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @infoperso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infopersos/1
  # DELETE /infopersos/1.json
  def destroy
    @infoperso.destroy
    respond_to do |format|
      format.html { redirect_to infopersos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_infoperso
      @infoperso = Infoperso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def infoperso_params
      params.require(:infoperso).permit(:pseudo, :age, :sexe, :ville, :departement, :pays)
    end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
def create
    @infoperso = Infoperso.find(params[:infoperso_id])
    @info = @infoperso.infos.create(params[:info].permit(:age_diagnostic,:pays_diagnostic,:autism_type, :trouble_psycho, :other_trouble))
    redirect_to infoperso_path(@infoperso)
  end

  def destroy
		@infoperso = Infoperso.find(params[:infoperso_id])
		@info = @infoperso.infos.find(params[:id])
		@info.destroy
		redirect_to infoperso_path(@infoperso)
	end

end

app/controllers/presentation_controller.rb
class PresentationController < ApplicationController
  def home
  end

  def inscription
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
  end

  def create
    user = User.find_by(pseudo: params[:session][:pseudo].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to infopersos_path
      # redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end




private

    def user_params
      params.require(:user).permit(:pseudo, :email, :password,
                                   :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/etats_helper.rb
module EtatsHelper
end

app/helpers/infopersos_helper.rb
module InfopersosHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/presentation_helper.rb
module PresentationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/infopersos/_form.html.erb
<%= form_for(@infoperso) do |f| %>
  <% if @infoperso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@infoperso.errors.count, "error") %> prohibited this infoperso from being saved:</h2>

      <ul>
      <% @infoperso.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pseudo %><br>
    <%= f.text_field :pseudo %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :sexe %><br>
    <%= f.text_field :sexe %>
  </div>
  <div class="field">
    <%= f.label :ville %><br>
    <%= f.text_field :ville %>
  </div>
  <div class="field">
    <%= f.label :departement %><br>
    <%= f.text_field :departement %>
  </div>
  <div class="field">
    <%= f.label :pays %><br>
    <%= f.text_field :pays %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infopersos/edit.html.erb
<h1>Editing infoperso</h1>

<%= render 'form' %>

<%= link_to 'Show', @infoperso %> |
<%= link_to 'Back', infopersos_path %>

app/views/infopersos/index.html.erb
<div class="row">
  <div class="small-2 large-4 columns" style="color :green">
    
    <%= image_tag("child128.png", alt: "Promo Image") %> 
  </div>
  
  
</div>
 

 <% @infopersos.each do |infoperso| %>
      <strong>
        <%= infoperso.pseudo %> <br>
        <%= infoperso.age %>   <br>
        <%= infoperso.sexe %>  <br>
        <%= infoperso.ville %> <br>
        <%= infoperso.departement %> <br>
        <%= infoperso.pays %>
        </strong>
        <%= link_to 'Show', infoperso %>
        <%= link_to 'Edit', edit_infoperso_path(infoperso) %>
        <%= link_to 'Destroy', infoperso, method: :delete, data: { confirm: 'Are you sure?' } %>
  

      

    <% end %>
  


<br>

<%= link_to 'New Infoperso', new_infoperso_path %>


 



 <!-- <div id="admin_page" style= "margin-top:-4px;">
  

  <%= link_to(root_path) do %>
                 <%= image_tag("child32.png", alt: "Promo Image") %> 
        
            <% end %> 

<%= link_to(root_path) do %>
                 <%= image_tag("edit32.png", alt: "Promo Image") %> 
            <% end %>


<%= link_to(root_path) do %>
                 <%= image_tag("eyes64.png", alt: "Promo Image") %> 
            <% end %>

<%= link_to(root_path) do %>
                 <%= image_tag("healt32.png", alt: "Promo Image") %> 
            <% end %>
<%= link_to(root_path) do %>
                 <%= image_tag("event32.png", alt: "Promo Image") %> 
            <% end %>
      
 </div>  -->
 


    

      
      
    
  

  
    

app/views/infopersos/new.html.erb
<h1>New infoperso</h1>

<%= render 'form' %>

<%= link_to 'Back', infopersos_path %>

app/views/infopersos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="small-2 large-4 columns">
    <p>

      <%= @infoperso.pseudo %>
    </p>

    <p>
      <%= @infoperso.age %> ans
    </p>

    <p>
      <%= @infoperso.sexe %>
    </p>
    <p>
      <%= @infoperso.ville %>(<%= @infoperso.departement %>), <%= @infoperso.pays %>
    </p>
  </div>
  
  
</div>

<!--............................................ Info du patients ..........................-->


<div class="row">
  <div class="small-4 large-6 columns">

    <dl class="tabs" data-tab>
      <dd class="active"><a href="#panel2-1">Infos patients</a></dd>
      <dd><a href="#panel2-2">Humour du jour</a></dd>
    </dl>
    <div class="tabs-content">
      <div class="content active" id="panel2-1">

        <h2>Information</h2>
        <% @infoperso.infos.each do |comment| %>
        <p>
         <strong>age de diagnostic</strong>
         <%= comment.age_diagnostic %>
       </p>

       <p>
         <strong>pays du diagnostic </strong>
         <%= comment.pays_diagnostic %>
       </p>

       <p>
         <strong>Type d'autisme</strong>
         <%= comment.autism_type %>
       </p>
       <p>
         <strong>Troubles psy </strong>
         <%= comment.trouble_psycho %>
       </p>
       <p>
         <strong>Autres troubles </strong>
         <%= comment.other_trouble %>
       </p>

       <p>
         <%= link_to 'Destroy ', [comment.infoperso, comment],
         method: :delete,
         data: { confirm: 'Are you sure?' } %>
       </p>
       <% end %>





       <p>
        <%= form_for([@infoperso, @infoperso.infos.build]) do |f| %>
        <p>
          <%= f.label :age_diagnostic , "Age de diagnostic" %><br />
          <%= f.text_field :age_diagnostic %>
        </p>
        <p>
          <%= f.label :pays_diagnostic , "Pays du diagnostic" %><br />
          <%= f.text_area :pays_diagnostic %>
        </p>

        <p>
          <%= f.label :autism_type , "Type d'autisme" %><br />
          <%= f.select :autism_type, [
            [" ", ""], 
            ["F840-autisme infantile", "F840-autisme infantile"], 
            ["F841-autisme atypique",   "F841-autisme infantile"], 
            ["F842-Syndrome de Rett",   "F842-Syndrome de Rett"],
            ["F843-Autre trouble désintégratif de l'enfance","F843-Autre trouble désintégratif de l'enfance"],
            ["F844-Hyperactivité associée à un retard mental et à des mouvements stéréotypés", "F844-Hyperactivité associée à un retard mental et à des mouvements stéréotypés"],
            ["F845-Syndrome de d'Asperger",   "F845-Syndrome de d'Asperger"],
            ["F848-Autres troubles envahissants du développmenent",   "F848-Autres troubles envahissants du développmenent"],
            ["F849-Troubles envahissants du développmenent,sans précision ",   "F849- Troubles envahissant du développmenent , sans précision"]
            ] %>
          </p>

          <p>
            <%= f.label :trouble_psycho , "Troubles du developpment psychologique"%><br />

            <%= f.select :trouble_psycho, [
              [" ", ""], 


              ["F800-Trouble spécifique de l'acquisition de l'articulation", "F800-Trouble spécifique de l'acquisition de l'articulation"], 

              ["F801-Trouble de l'acquisition du langage,  de type expressif",   "F801-Trouble de l'acquisition du langage,  de type expressif"],

              ["F802-Trouble de l'acquisition du langage,  de type réceptif",   "F802-Trouble de l'acquisition du langage,  de type réceptif"], 

              ["F803-Aphasie acquise avec épilepsie[Landau-Kleffner]",   "F802-Aphasie acquise avec épilepsie[Landau-Kleffner]"],

              ["F808-Autres troubles du développement de la parole et du langage",   "F808-Autres troubles du développement de la parole et du langage"],

              ["F809-Troubles du developpment de la parole et du langage, sans précision",   "F809-Troubles du developpment de la parole et du langage, sans précision"],

              ["F810-Trouble de l'acquisition de la lecture",   "F810-Trouble de l'acquisition de la lecture"],

              ["F811-Trouble de l'acquisition de l'orthographe",   "F811-Trouble de l'acquisition de l'orthographe"],
              ["F812-Trouble de l'acquisition de l'arithmétique",   "F812-Trouble de l'acquisition de l'arithmétique"],

              ["F813-Trouble mixte des acquisitions scolaire",   "F813-Trouble mixte des acquisitions scolaire"],

              ["F818-Autres troubles du développement",   "F818-Autres troubles du développement"],

              ["F819-Trouble du developpment, des acquisitions scolaires, sans précision",   "F819-Trouble du developpment, des acquisitions scolaires, sans précision"],

              ["F82-Troubles spécifique du développement moteur",   "F82-Troubles spécifique du développement moteur"],

              ["F83-Troubles spécifiques mixte du développement",   "F83-Troubles spécifiques mixte du développement"],

              ["F840- Autisme infantile",   "F-Autres Autisme infantile"],

              ["F841-Autisme atypique",   "F841-Autisme atypique"],

              ["F842-Syndrome de Rett",   "F842-Syndrome de Rett"],
              ["F843-Autre trouble désintégratif de l'enfance",   "F843-Autre trouble désintégratif de l'enfance"],

              ["F844-Hyperactivité associée à un retard mental et à des mouvements",   "F844-Hyperactivité associée à un retard mental et à des mouvements"],

              ["F845-Syndrome d'Asperger",   "F845-Syndrome d'Asperger"],

              ["F849-Troubles envahissants du développement",   "F849-Troubles envahissants du développement"],
              ["F88-Autres troubles du développement psychologique",   "F88-Autres troubles du développement psychologique"],

              ["F849-Trouble du développment psychologique",   "F849-Trouble du développment psychologique"],
              ]%>

            </p>
            <p>
              <%= f.label :other_trouble , "Autres troubles"%><br />


              <%= f.select :other_trouble, [
                [" ", ""], 

                ["F000-Démence de la maladie d'Alzheimer, à début précoce(G30.0)", "F000-Démence de la maladie d'Alzheimer, à début précoce(G30.0)"], 
                ["F001-Démence de la maladie d'Alzheimer, à début tardif(G30.1)", "F000-Démence de la maladie d'Alzheimer, à début tardif(G30.1)"], 
                ["F002-Démence de la maladie d'Alzheimer, forme atypique ou mixte(G30.8)", "F000-Démence de la maladie d'Alzheimer, forme atypique ou mixte(G30.8)"],
                ["F009-Démence de la maladie d'Alzheimer, sans précision(G30.9)", "F000-Démence de la maladie d'Alzheimer, sans précision(G30.9)"], 

                ["F010-Démence vasculaire à début aigu", "F000-Démence vasculaire à début aigu"], 
                ["F011-Démence vasculaire par infractus multiples", "F011-Démence vasculaire par infractus multiples"], 
                ["F010-Démence vasculaire à début aigu", "F000-Démence vasculaire à début aigu"], 
                ["F012-Démence vasculaire sous-corticale", "F012-Démence vasculaire sous corticale"], 
                ["F013-Démence vasculaire mixte, corticale et sous-corticale", "F013-Démence vasculaire mixte, corticale et sous-corticale"], 
                ["F018-Autres formes de démence vasculaire ", "F018-Autres formes de démence vasculaire "], 
                ["F019-Démence vasculaire, sans précision", "F019-Démence vasculaire, sans précision"],



                ["F021-Démence de la maladie de Creutzfeld-Jakob(A81.0)", "F021-Démence de la maladie de Creutzfeld-Jakob(A81.0)"], 
                ["F022-Démence de la maladie de Huntington(G10)", "F022-Démence de la maladie de Huntington(G10)"], 
                ["F023-Démence de la maladie de Parkinson(G20)", "F023-Démence de la maladie de Parkinson(G20)"], 
                ["F024-Démence de la maladie de la maladie due au VIH(B22.0)", "F024-Démence de la maladie de la maladie due au VIH(B22.0)"], 

                ["F028-Démence en cours d'autres maladies classées ailleurs", "F028-Démence en cours d'autres maladies classées ailleurs"], 
                ["F03-Démence, sans précision", "F03-Démence, sans précision"], 


                ["F009-Démence de la maladie d'Alzheimer, sans précision(G30.9)", "F000-Démence de la maladie d'Alzheimer, sans précision(G30.9)"], 

                ["F009-Démence de la maladie d'Alzheimer, sans précision(G30.9)", "F000-Démence de la maladie d'Alzheimer, sans précision(G30.9)"], 

                ["F009-Démence de la maladie d'Alzheimer, sans précision(G30.9)", "F000-Démence de la maladie d'Alzheimer, sans précision(G30.9)"], 

                ["F009-Démence de la maladie d'Alzheimer, sans précision(G30.9)", "F000-Démence de la maladie d'Alzheimer, sans précision(G30.9)"],  

                ]%>
              </p>

              <p>
                <%= f.submit %>
              </p>

              <% end -%>

            </p>
          </div>
          <div class="content" id="panel2-2">
            <p>

              <h2>Information</h2>
              <% @infoperso.etats.each do |comment| %>
              <p>
               <strong>Humeur du jour</strong>
               <%= comment.humor %>
             </p>

             <p>
               <strong>Evénement  </strong>
               <%= comment.event %>
             </p>

             <p>
               <%= link_to 'Destroy ', [comment.infoperso, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
             </p>
             <% end %>


             <!-- Formulaire humeur & event -->
             <p>
              <%= form_for([@infoperso, @infoperso.etats.build]) do |f| %>
              <p>
                <%= f.label :humor , "Humeur du jour" %><br />
                <%= f.radio_button :humor, "1" %> Bien  
                <%= f.radio_button :humor, "0" %> Pas bien 
              </p>
              <p>
                <%= f.label :event , "evénement" %><br />
                <%= f.text_area :event %>
              </p>
              <p>
                <%= f.submit %>
              </p>
              <% end -%>
              



              <p>
              </p>
            </div>
          </div>











          <%= link_to 'Edit', edit_infoperso_path(@infoperso) %> |
          <%= link_to 'Back', infopersos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Autispart" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  

  </head>
  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
    
  </body>
</html>

app/views/presentation/home.html.erb
<%= link_to "se connecter",   signin_path %>
<h3 style="font-size: 33px;padding-top: 191px;margin-left:64px ; font-family: 'desyrelregular';"> 
  " L'autisme est un soleil inversé : ses rayons sont dirigés vers l'intérieur " 
</h3>

<div id="login"></div>

  <a href="" title=""> <%= link_to "Inscrire", signup_path , class:"button expand" , style: 'background-color: #00463F' %></a>
  


<!-- <a href="#" class="button expand" style= " margin-top: -44px; background-color: #00463F;
" >
  Inscrivez-vous
</a> -->

<div class="row" style=" margin-top: 104px; margin-left: 136px;">
  <div class="small-2 large-4 columns" class="circular"> 
    <div class="circular"> 
      <p style="padding-top: 16px;margin-left: 83px;"> 
      <%= image_tag("parents32.png", alt: "Promo Image") %> 
        </p> 
    </div>
  </div>
  <div class="small-4 large-4 columns">
    <div class="circular1"> 
      <p style="padding-top: 9px; margin-left: 65px"> 
        <%= image_tag("heart64.png", alt: "Promo Image") %> 
      </p>  
    </div>
  </div>
  <div class="small-6 large-4 columns">
    <div class="circular2">
      <p style="padding-top: 6px;padding-left: 62px;"> 
        <%= image_tag("prog64.png", alt: "Promo Image") %> 
      </p> 
    </div>
  </div>
</div>

app/views/presentation/inscription.html.erb
 
 <div id="admin_page" style= "margin-top:-4px;">
 	

 	<%= link_to(root_path) do %>
                 <%= image_tag("child32.png", alt: "Promo Image") %> 
				
            <% end %>	

<%= link_to(root_path) do %>
                 <%= image_tag("edit32.png", alt: "Promo Image") %> 
            <% end %>


<%= link_to(root_path) do %>
                 <%= image_tag("eyes64.png", alt: "Promo Image") %> 
            <% end %>

<%= link_to(root_path) do %>
                 <%= image_tag("healt32.png", alt: "Promo Image") %> 
            <% end %>
<%= link_to(root_path) do %>
                 <%= image_tag("event32.png", alt: "Promo Image") %> 
            <% end %>
<%= link_to(signout_path, method: "delete" ) do %>
                 <%= image_tag("off32.png", alt: "Promo Image") %> 
            <% end %>
             
 </div> 








<h1>Bonjour</h1>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pseudo %><br>
    <%= f.text_field :pseudo %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :sexe %><br>
    <%= f.text_field :sexe %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :ville %><br>
    <%= f.text_field :ville %>
  </div>
  <div class="field">
    <%= f.label :departement %><br>
    <%= f.text_field :departement %>
  </div>
  <div class="field">
    <%= f.label :pays %><br>
    <%= f.text_field :pays %>
  </div>

  <%= f.password_field :attribute %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Pseudo</th>
      <th>Name</th>
      <th>Prenom</th>
      <th>Email</th>
      <th>Sexe</th>
      <th>Age</th>
      <th>Ville</th>
      <th>Departement</th>
      <th>Pays</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.pseudo %></td>
        <td><%= user.name %></td>
        <td><%= user.prenom %></td>
        <td><%= user.email %></td>
        <td><%= user.sexe %></td>
        <td><%= user.age %></td>
        <td><%= user.ville %></td>
        <td><%= user.departement %></td>
        <td><%= user.pays %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :pseudo %>
      <%= f.text_field :pseudo %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
 
 <div id="admin_page" style= "margin-top:-4px;">
 	

 	<%= link_to(root_path) do %>
                 <%= image_tag("child32.png", alt: "Promo Image") %> 
				
            <% end %>	

<%= link_to(root_path) do %>
                 <%= image_tag("edit32.png", alt: "Promo Image") %> 
            <% end %>


<%= link_to(root_path) do %>
                 <%= image_tag("eyes64.png", alt: "Promo Image") %> 
            <% end %>

<%= link_to(root_path) do %>
                 <%= image_tag("healt32.png", alt: "Promo Image") %> 
            <% end %>
<%= link_to(root_path) do %>
                 <%= image_tag("event32.png", alt: "Promo Image") %> 
            <% end %>
<%= link_to(signout_path, method: "delete" ) do %>
                 <%= image_tag("off32.png", alt: "Promo Image") %> 
            <% end %>
         
      <strong> Bonjour <%= @user.pseudo %> </strong>    
 </div> 








<h1>Bonjour</h1>